#!/bin/bash

# Config
MINER_INSTALLER_DIR=$1
CLAYMORE_MINER_GZIP=$2
CLAYMORE_DIR=$3

mkdir -p $CLAYMORE_DIR
tar xvzf "${MINER_INSTALLER_DIR}/miner/${CLAYMORE_MINER_GZIP}.gz" -C $CLAYMORE_DIR --strip-components 1
