#!/bin/bash

MINER_START_SCRIPT=$1
MINER_DIR=$2

touch $MINER_START_SCRIPT
echo -e "#!/bin/bash

export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100

${MINER_DIR}/ethminer --farm-recheck 200 -U -RH -SE [MINER_EMAIL] -P stratum1+tcp://[ETH_WALLET_ADDR].[WORKER_NAME]@[POOL]

" > ${MINER_START_SCRIPT}
